export const CATEGORIES = [
  "Common Scenarios",
  "Services",
  "Quality Parameters",
  "Products",
  "Escalated Cases Templates",
  "Community Related",
  "App Related",
  "Available Rewards",
  "Website Related",
  "SIM Activation",
  "Managing Account",
  "Cards and Codes",
  "About us",
  "Payments",
  "Orders and Deliveries",
  "Khoros Tags",
  "Communication Etiquette/Channels",
  "Jawwy Systems",
  "Troubleshooting",
];
